# Generated by Django 6.0.6 on 2026-06-17 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名称')),
            ],
            options={
                'verbose_name': '鞋品牌',
                'verbose_name_plural': '鞋品牌',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('level', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('professional', '专业')], default='beginner', max_length=20, verbose_name='级别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoeFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('last_type', models.CharField(max_length=100, verbose_name='楦型')),
                ('hardness', models.CharField(choices=[('soft', '软'), ('medium', '中等'), ('hard', '硬')], default='medium', max_length=10, verbose_name='硬度')),
                ('box_height', models.CharField(choices=[('low', '低'), ('medium', '中等'), ('high', '高')], default='medium', max_length=10, verbose_name='鞋盒高度')),
                ('ribbon_style', models.CharField(choices=[('cross', '交叉式'), ('straight', '直绑式'), ('wrap', '缠绕式')], default='cross', max_length=10, verbose_name='缎带固定方式')),
                ('size', models.CharField(max_length=20, verbose_name='鞋码')),
                ('fit_result', models.CharField(choices=[('excellent', '非常合适'), ('good', '较合适'), ('fair', '一般'), ('poor', '不合适')], default='good', max_length=10, verbose_name='适配结果')),
                ('fitting_date', models.DateField(verbose_name='试鞋日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_fittings', to='pointe.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '试鞋记录',
                'verbose_name_plural': '试鞋记录',
                'ordering': ['-fitting_date'],
            },
        ),
        migrations.CreateModel(
            name='FootProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_length', models.FloatField(verbose_name='脚长(mm)')),
                ('foot_width', models.FloatField(verbose_name='脚宽(mm)')),
                ('arch_height', models.CharField(choices=[('low', '低足弓'), ('medium', '正常足弓'), ('high', '高足弓')], default='medium', max_length=10, verbose_name='足弓高度')),
                ('instep_strength', models.CharField(choices=[('weak', '较弱'), ('medium', '中等'), ('strong', '较强')], default='medium', max_length=10, verbose_name='脚背力量')),
                ('past_injuries', models.TextField(blank=True, verbose_name='既往伤痛')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foot_profile', to='pointe.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '足型档案',
                'verbose_name_plural': '足型档案',
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='训练日期')),
                ('duration_minutes', models.IntegerField(verbose_name='上鞋时长(分钟)')),
                ('stability', models.CharField(choices=[('excellent', '非常稳定'), ('good', '较稳定'), ('fair', '一般'), ('poor', '不稳定')], default='good', max_length=10, verbose_name='足尖稳定度')),
                ('pain_location', models.CharField(choices=[('none', '无疼痛'), ('toe', '脚趾'), ('ball', '前脚掌'), ('arch', '足弓'), ('heel', '脚跟'), ('ankle', '脚踝'), ('instep', '脚背'), ('multiple', '多部位')], default='none', max_length=10, verbose_name='疼痛部位')),
                ('pain_level', models.IntegerField(default=0, verbose_name='疼痛等级(0-10)')),
                ('sole_softening', models.CharField(choices=[('none', '无明显软化'), ('slight', '轻微软化'), ('moderate', '中度软化'), ('severe', '严重软化')], default='none', max_length=10, verbose_name='鞋底软化程度')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('shoe_fitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs', to='pointe.shoefitting', verbose_name='关联鞋子')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='pointe.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '训练日志',
                'verbose_name_plural': '训练日志',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WearAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('replace', '建议换鞋'), ('insole', '建议调整鞋垫'), ('hardness', '建议调整硬度'), ('check', '建议检查')], default='replace', max_length=10, verbose_name='预警类型')),
                ('reason', models.TextField(verbose_name='预警原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('acknowledged', '已确认'), ('resolved', '已解决')], default='pending', max_length=15, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('shoe_fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wear_alerts', to='pointe.shoefitting', verbose_name='关联鞋子')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wear_alerts', to='pointe.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '磨损预警',
                'verbose_name_plural': '磨损预警',
                'ordering': ['-created_at'],
            },
        ),
    ]
