# Generated by Django 6.0.6 on 2026-06-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearalert',
            name='actual_followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际回访日期'),
        ),
        migrations.AddField(
            model_name='wearalert',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处置时间'),
        ),
        migrations.AddField(
            model_name='wearalert',
            name='handler',
            field=models.CharField(blank=True, max_length=100, verbose_name='处置人'),
        ),
        migrations.AddField(
            model_name='wearalert',
            name='handling_notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='wearalert',
            name='handling_plan',
            field=models.TextField(blank=True, verbose_name='处置方案'),
        ),
        migrations.AddField(
            model_name='wearalert',
            name='suggested_followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='建议回访日期'),
        ),
        migrations.AlterField(
            model_name='wearalert',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('acknowledged', '已确认'), ('handled', '已处置'), ('followup', '待回访'), ('resolved', '已解决')], default='pending', max_length=15, verbose_name='状态'),
        ),
    ]
