# Generated by Django 6.0.6 on 2026-06-17 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointe', '0002_wearalert_actual_followup_date_wearalert_handled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointeShoeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_type', models.CharField(choices=[('pointe', '足尖鞋'), ('slipper', '训练软鞋'), ('sample', '样鞋')], default='pointe', max_length=20, verbose_name='鞋类型')),
                ('brand', models.CharField(max_length=100, verbose_name='品牌')),
                ('last_type', models.CharField(max_length=100, verbose_name='楦型')),
                ('size', models.CharField(max_length=20, verbose_name='尺码')),
                ('width', models.CharField(blank=True, max_length=10, verbose_name='鞋宽')),
                ('hardness', models.CharField(choices=[('soft', '软'), ('medium', '中等'), ('hard', '硬'), ('extra_hard', '特硬')], default='medium', max_length=20, verbose_name='硬度')),
                ('box_height', models.CharField(choices=[('low', '低'), ('medium', '中等'), ('high', '高')], default='medium', max_length=10, verbose_name='鞋盒高度')),
                ('shank_type', models.CharField(blank=True, max_length=50, verbose_name='鞋底类型')),
                ('status', models.CharField(choices=[('available', '可借用'), ('borrowed', '已借出'), ('maintenance', '维护中'), ('reserved', '已预留'), ('retired', '已退役'), ('lost', '已丢失')], default='available', max_length=20, verbose_name='当前状态')),
                ('classroom', models.CharField(blank=True, max_length=100, verbose_name='所在教室')),
                ('cabinet', models.CharField(blank=True, max_length=50, verbose_name='柜位')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购入日期')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='入库日期')),
                ('max_borrow_count', models.IntegerField(default=10, verbose_name='最大可借用次数')),
                ('current_borrow_count', models.IntegerField(default=0, verbose_name='已借用次数')),
                ('safety_stock', models.IntegerField(default=1, verbose_name='安全库存数量')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='购入价格')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '鞋款库存',
                'verbose_name_plural': '鞋款库存',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoeBorrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('fitting', '试穿预约'), ('training', '训练借用'), ('performance', '演出借用'), ('rehearsal', '排练借用'), ('testing', '样鞋测试'), ('other', '其他')], default='training', max_length=20, verbose_name='借用用途')),
                ('expected_start_time', models.DateTimeField(verbose_name='预计开始时间')),
                ('expected_end_time', models.DateTimeField(verbose_name='预计归还时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际借出时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
                ('status', models.CharField(choices=[('reserved', '已预约'), ('borrowed', '已借出'), ('returned', '已归还'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='reserved', max_length=20, verbose_name='状态')),
                ('reservation_notes', models.TextField(blank=True, verbose_name='预约备注')),
                ('borrow_notes', models.TextField(blank=True, verbose_name='借出备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='pointe.pointeshoeinventory', verbose_name='鞋款')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_borrowings', to='pointe.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '借用排班',
                'verbose_name_plural': '借用排班',
                'ordering': ['-expected_start_time'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overdue', '借用逾期'), ('abnormal_return', '归还异常'), ('low_stock', '库存不足'), ('high_borrow_count', '借用次数过高'), ('maintenance_due', '待维护'), ('lost', '已丢失')], max_length=20, verbose_name='提醒类型')),
                ('message', models.TextField(verbose_name='提醒内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('acknowledged', '已确认'), ('resolved', '已解决'), ('dismissed', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('handled_by', models.CharField(blank=True, max_length=100, verbose_name='处理人')),
                ('handling_notes', models.TextField(blank=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='pointe.student', verbose_name='关联学员')),
                ('shoe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pointe.pointeshoeinventory', verbose_name='关联鞋款')),
                ('borrowing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pointe.shoeborrowing', verbose_name='关联借用单')),
            ],
            options={
                'verbose_name': '库存提醒',
                'verbose_name_plural': '库存提醒',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoeReturnCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='归还日期')),
                ('overall_condition', models.CharField(choices=[('excellent', '完好'), ('good', '良好'), ('fair', '一般'), ('poor', '破损')], default='good', max_length=10, verbose_name='整体状况')),
                ('abnormal_type', models.CharField(choices=[('none', '无异常'), ('dirty', '污渍'), ('damaged', '破损'), ('worn', '严重磨损'), ('missing_part', '配件缺失'), ('wrong_size', '尺码错误'), ('other', '其他')], default='none', max_length=20, verbose_name='异常类型')),
                ('abnormal_description', models.TextField(blank=True, verbose_name='异常说明')),
                ('cleaning_needed', models.BooleanField(default=False, verbose_name='需要清洁')),
                ('repair_needed', models.BooleanField(default=False, verbose_name='需要维修')),
                ('retire_shoe', models.BooleanField(default=False, verbose_name='建议退役')),
                ('checked_by', models.CharField(blank=True, max_length=100, verbose_name='检查人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('borrowing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_check', to='pointe.shoeborrowing', verbose_name='借用单')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_checks', to='pointe.pointeshoeinventory', verbose_name='鞋款')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_checks', to='pointe.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '归还检查',
                'verbose_name_plural': '归还检查',
                'ordering': ['-return_date'],
            },
        ),
    ]
