# Generated by Django 6.0.6 on 2026-06-17 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointe', '0003_pointeshoeinventory_shoeborrowing_inventoryalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeborrowing',
            name='fitting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowings', to='pointe.shoefitting', verbose_name='关联试鞋记录'),
        ),
        migrations.AlterField(
            model_name='pointeshoeinventory',
            name='entry_date',
            field=models.DateField(auto_now_add=True, verbose_name='入库日期'),
        ),
    ]
