# Generated by Django 6.0.6 on 2026-06-17 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointe', '0004_shoeborrowing_fitting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('target_level', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('professional', '专业')], max_length=20, verbose_name='训练级别目标')),
                ('weekly_max_duration', models.IntegerField(verbose_name='每周上鞋时长上限(分钟)')),
                ('key_exercises', models.TextField(verbose_name='重点练习动作')),
                ('forbidden_exercises', models.TextField(blank=True, verbose_name='禁忌动作')),
                ('strength_training', models.TextField(blank=True, verbose_name='辅助力量训练')),
                ('evaluation_criteria', models.TextField(verbose_name='阶段评估标准')),
                ('responsible_teacher', models.CharField(max_length=100, verbose_name='负责教师')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('paused', '已暂停'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('risk_level', models.CharField(choices=[('normal', '正常'), ('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='normal', max_length=20, verbose_name='风险等级')),
                ('risk_reasons', models.TextField(blank=True, verbose_name='风险原因')),
                ('adjustment_suggestion', models.CharField(choices=[('downgrade', '建议降级训练'), ('pause', '建议暂停上鞋'), ('insole', '建议调整鞋垫'), ('refit', '建议重新试鞋'), ('strengthen', '建议加强力量训练'), ('stretch', '建议增加拉伸'), ('none', '无需调整')], default='none', max_length=20, verbose_name='调整建议')),
                ('adjustment_notes', models.TextField(blank=True, verbose_name='调整说明')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('foot_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans', to='pointe.footprofile', verbose_name='足型档案')),
                ('shoe_fitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans', to='pointe.shoefitting', verbose_name='试鞋记录')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='pointe.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '训练计划',
                'verbose_name_plural': '训练计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(verbose_name='评估日期')),
                ('phase_name', models.CharField(max_length=100, verbose_name='评估阶段')),
                ('target_achievement', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '未达标')], default='good', max_length=20, verbose_name='目标达成情况')),
                ('stability_evaluation', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '未达标')], default='good', max_length=20, verbose_name='稳定度评估')),
                ('strength_evaluation', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '未达标')], default='good', max_length=20, verbose_name='力量评估')),
                ('pain_status', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '未达标')], default='good', max_length=20, verbose_name='疼痛状况')),
                ('overall_result', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '未达标')], default='good', max_length=20, verbose_name='总体评估结果')),
                ('progress_suggestion', models.CharField(choices=[('promote', '建议晋级'), ('continue', '继续当前阶段'), ('adjust', '调整计划后继续'), ('regress', '建议降级')], default='continue', max_length=20, verbose_name='发展建议')),
                ('improvement_points', models.TextField(blank=True, verbose_name='改进要点')),
                ('next_phase_goals', models.TextField(blank=True, verbose_name='下一阶段目标')),
                ('evaluator', models.CharField(max_length=100, verbose_name='评估人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_evaluations', to='pointe.trainingplan', verbose_name='训练计划')),
            ],
            options={
                'verbose_name': '阶段评估',
                'verbose_name_plural': '阶段评估',
                'ordering': ['training_plan', '-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(verbose_name='周次')),
                ('week_start_date', models.DateField(verbose_name='周开始日期')),
                ('week_end_date', models.DateField(verbose_name='周结束日期')),
                ('actual_duration', models.IntegerField(default=0, verbose_name='实际完成时长(分钟)')),
                ('exercise_completion', models.CharField(choices=[('excellent', '优秀(≥90%)'), ('good', '良好(70-89%)'), ('fair', '一般(50-69%)'), ('poor', '较差(<50%)')], default='good', max_length=20, verbose_name='动作完成度')),
                ('stability_score', models.IntegerField(blank=True, null=True, verbose_name='稳定度评分(0-100)')),
                ('pain_location', models.CharField(choices=[('none', '无疼痛'), ('toe', '脚趾'), ('ball', '前脚掌'), ('arch', '足弓'), ('heel', '脚跟'), ('ankle', '脚踝'), ('instep', '脚背'), ('multiple', '多部位')], default='none', max_length=20, verbose_name='疼痛部位')),
                ('pain_level', models.IntegerField(default=0, verbose_name='疼痛等级(0-10)')),
                ('teacher_comments', models.TextField(blank=True, verbose_name='教师评语')),
                ('needs_adjustment', models.BooleanField(default=False, verbose_name='是否需要调整计划')),
                ('adjustment_reason', models.TextField(blank=True, verbose_name='调整原因')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='是否已提交')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('submitted_by', models.CharField(blank=True, max_length=100, verbose_name='提交人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_records', to='pointe.trainingplan', verbose_name='训练计划')),
            ],
            options={
                'verbose_name': '周执行记录',
                'verbose_name_plural': '周执行记录',
                'ordering': ['training_plan', 'week_number'],
                'unique_together': {('training_plan', 'week_number')},
            },
        ),
    ]
