# Generated by Django 6.0.6 on 2026-06-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointe', '0005_trainingplan_phaseevaluation_weeklyexecutionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='adjustment_suggestion',
            field=models.CharField(choices=[('none', '无需调整'), ('downgrade', '建议降级训练'), ('pause', '建议暂停上鞋'), ('insole', '建议调整鞋垫'), ('refit', '建议重新试鞋'), ('strengthen', '建议加强力量训练'), ('stretch', '建议增加拉伸')], default='none', max_length=20, verbose_name='调整建议'),
        ),
        migrations.CreateModel(
            name='InjuryIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_source', models.CharField(choices=[('pain', '训练疼痛'), ('wear_alert', '磨损预警'), ('plan_risk', '计划风险'), ('teacher_observation', '教师观察'), ('student_report', '学员反馈'), ('followup_review', '复查发现')], max_length=20, verbose_name='触发来源')),
                ('pain_location', models.CharField(choices=[('toe', '脚趾'), ('ball', '前脚掌'), ('arch', '足弓'), ('heel', '脚跟'), ('ankle', '脚踝'), ('instep', '脚背'), ('multiple', '多部位')], max_length=20, verbose_name='疼痛部位')),
                ('pain_level', models.IntegerField(verbose_name='疼痛等级(0-10)')),
                ('suspected_cause', models.TextField(blank=True, verbose_name='疑似原因')),
                ('intervention_measures', models.TextField(verbose_name='干预措施')),
                ('suspend_days', models.IntegerField(default=0, verbose_name='暂停上鞋天数')),
                ('rehab_training', models.TextField(blank=True, verbose_name='康复训练内容')),
                ('responsible_teacher', models.CharField(max_length=100, verbose_name='负责教师')),
                ('next_review_date', models.DateField(verbose_name='复查日期')),
                ('status', models.CharField(choices=[('active', '干预中'), ('paused', '暂停观察'), ('closed', '已关闭')], default='active', max_length=10, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('related_training_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='pointe.trainingplan', verbose_name='关联训练计划')),
                ('related_wear_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='pointe.wearalert', verbose_name='关联磨损预警')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_interventions', to='pointe.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '伤痛干预单',
                'verbose_name_plural': '伤痛干预单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('continuous_pain', '连续高疼痛'), ('review_overdue', '复查逾期'), ('pain_recurrence', '恢复上鞋后再疼痛'), ('high_pain_level', '高疼痛等级')], max_length=20, verbose_name='提醒类型')),
                ('message', models.TextField(verbose_name='提醒内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('acknowledged', '已确认'), ('resolved', '已解决'), ('dismissed', '已忽略')], default='pending', max_length=15, verbose_name='状态')),
                ('handled_by', models.CharField(blank=True, max_length=100, verbose_name='处理人')),
                ('handling_notes', models.TextField(blank=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pointe.injuryintervention', verbose_name='关联干预单')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_reminders', to='pointe.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '干预风险提醒',
                'verbose_name_plural': '干预风险提醒',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RehabilitationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(verbose_name='复查日期')),
                ('pain_level', models.IntegerField(verbose_name='当前疼痛等级(0-10)')),
                ('pain_change', models.CharField(choices=[('improved', '疼痛减轻'), ('stable', '疼痛稳定'), ('worsened', '疼痛加重')], max_length=10, verbose_name='疼痛变化')),
                ('stability_recovery', models.CharField(choices=[('excellent', '恢复良好'), ('good', '有所恢复'), ('fair', '恢复一般'), ('poor', '无明显恢复')], max_length=10, verbose_name='稳定度恢复情况')),
                ('allow_resume_pointe', models.BooleanField(default=False, verbose_name='是否允许恢复上鞋')),
                ('need_refit', models.BooleanField(default=False, verbose_name='是否需要重新试鞋')),
                ('need_insole_adjust', models.BooleanField(default=False, verbose_name='是否需要调整鞋垫')),
                ('review_notes', models.TextField(blank=True, verbose_name='复查备注')),
                ('reviewer', models.CharField(max_length=100, verbose_name='复查人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pointe.injuryintervention', verbose_name='干预单')),
            ],
            options={
                'verbose_name': '康复复查',
                'verbose_name_plural': '康复复查',
                'ordering': ['-review_date'],
            },
        ),
    ]
